search_strings = [ [ "AAAAATEy", "EA\r\nAABI" ], [ "T8hlGOo9", "OKl2N\r\nC", "AAAAAAAA" ], [ "3r0TRZfh", "AAAAAAAA" ], [ "\n/s1Caa6", "J1Ls9RWH" ], [ "://44449" ], [ "://84371" ], [ "://87756" ], [ "://94654" ] ]
