address_tag = "[EXT]"

name_domain_list = "My Company"

clean_text = true
clean_html = true

subject_tag = "[EXTERNAL]"

text_tag = "###### EXTERNAL SENDER ######\n"

text_position = "top"

html_tag = "###### EXTERNAL SENDER ######\n"

html_position = "top"

html_tag_id = "tag_mail_1"
